- name: Install System Packages 1 (build-essential, cmake, pkg-config)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]
  tags: always
  
- name: Install System Packages 2 (lua, unzip)
  become: true
  apt:
    name: ["lua5.1", "unzip"]
  tags: always
  
- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: ["compton", "curl", "htop", "lsof", "i3", "python3-pip", "dconf-editor", "moreutils", "ubuntu-mate-desktop" ]
  tags: always
  
- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags: always

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags: always
