- name: Installing stow
  become: true
  apt: name=stow
  tags: always

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:jmehrs/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: always

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags: always
