- name: Remove neovim
  shell: rm -rf ~/neovim
  tags: always
  
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags: always
  
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags: always
  
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags: always
  
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags: always
  
- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  tags: always
  
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags: always
  
